# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: export BROWSERSTACK_USERNAME='amitpunjabi2'
- script: export BROWSERSTACK_ACCESS_KEY='Mb6R9PKpdrnkxxK3GMNE'
- script: echo Hello, world!
- script: npm install
- script: npm run single
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
